/**
 * Copyright (C) 2009-2011, Shao Miller <shao.miller@yrdsb.edu.on.ca>.
 * Copyright 2006-2008, V.
 * For WinAoE contact information, see http://winaoe.org/
 *
 * This file is part of WinVBlock, derived from WinAoE.
 *
 * WinVBlock is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WinVBlock is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WinVBlock.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * Disk device specifics.
 */

#include <ntddk.h>

#include "portable.h"
#include "winvblock.h"
#include "wv_stdlib.h"
#include "irp.h"
#include "driver.h"
#include "bus.h"
#include "device.h"
#include "disk.h"
#include "debug.h"

#ifndef _MSC_VER
static long long __divdi3(long long u, long long v) {
    return u / v;
  }
#endif

/* IRP_MJ_DEVICE_CONTROL dispatcher from disk/dev_ctl.c */
extern WV_F_DEV_CTL disk_dev_ctl__dispatch;
/* IRP_MJ_SCSI dispatcher from disk/scsi.c */
extern WV_F_DEV_SCSI disk_scsi__dispatch;
/* IRP_MJ_PNP dispatcher from disk/pnp.c */
extern WV_F_DEV_PNP disk_pnp__dispatch;

/* Forward declarations. */
static WV_F_DEV_FREE WvDiskDevFree_;
static WV_F_DEV_DISPATCH WvDiskIrpPower_;
static WV_F_DEV_DISPATCH WvDiskIrpSysCtl_;
static WV_F_DISK_INIT WvDiskDefaultInit_;
static WV_F_DISK_CLOSE WvDiskDefaultClose_;

/* Globals. */
static LIST_ENTRY WvDiskList_;
static KSPIN_LOCK WvDiskListLock_;
BOOLEAN WvDiskIsRemovable[WvlDiskMediaTypes] = { TRUE, FALSE, TRUE };
PWCHAR WvDiskCompatIds[WvlDiskMediaTypes] = {
    L"GenSFloppy",
    L"GenDisk",
    L"GenCdRom"
  };
/* Device IRP major function dispatch table. */
WV_S_DEV_IRP_MJ WvDiskIrpMj_ = {
    WvDiskIrpPower_,
    WvDiskIrpSysCtl_,
    disk_dev_ctl__dispatch,
    disk_scsi__dispatch,
    disk_pnp__dispatch,
  };

static UINT32 WvDiskDefaultMaxXferLen_(IN WV_SP_DISK_T disk) {
    return 1024 * 1024;
  }

/* Initialize a disk. */
static BOOLEAN STDCALL WvDiskDevInit_(IN WV_SP_DEV_T dev) {
    WV_SP_DISK_T disk = disk__get_ptr(dev);

    /* Use the disk operation, if there is one. */
    if (disk->disk_ops.Init)
      return disk->disk_ops.Init(disk);
    return TRUE;
  }

static BOOLEAN STDCALL WvDiskDefaultInit_(IN WV_SP_DISK_T disk) {
    return TRUE;
  }

static VOID STDCALL WvDiskDevClose_(IN WV_SP_DEV_T dev) {
    WV_SP_DISK_T disk = disk__get_ptr(dev);

    /* Use the disk operation, if there is one. */
    if (disk->disk_ops.Close)
      disk->disk_ops.Close(disk);
    return;
  }

static VOID STDCALL WvDiskDefaultClose_(IN WV_SP_DISK_T disk) {
    return;
  }

static NTSTATUS STDCALL WvDiskIrpPower_(IN WV_SP_DEV_T dev, IN PIRP irp) {
    PoStartNextPowerIrp(irp);
    return WvlIrpComplete(irp, 0, STATUS_NOT_SUPPORTED);
  }

static NTSTATUS STDCALL WvDiskIrpSysCtl_(IN WV_SP_DEV_T dev, IN PIRP irp) {
    return WvlIrpComplete(irp, 0, irp->IoStatus.Status);
  }

/**
 * Create a disk PDO filled with the given disk parameters.
 *
 * @v dev_ptr           Populate PDO dev. ext. space from these details.
 * @ret dev_obj_ptr     Points to the new PDO, or is NULL upon failure.
 *
 * Returns a Physical Device Object pointer on success, NULL for failure.
 */
static PDEVICE_OBJECT STDCALL WvDiskCreatePdo_(IN WV_SP_DEV_T dev_ptr) {
    /* Used for pointing to disk details. */
    WV_SP_DISK_T disk_ptr;
    /* Status of the last operation. */
    NTSTATUS status;
    /* The new node's physical device object (PDO). */
    PDEVICE_OBJECT dev_obj_ptr;
    /* Floppy, hard disk, optical disc specifics. */
    static DEVICE_TYPE disk_types[WvlDiskMediaTypes] =
      { FILE_DEVICE_DISK, FILE_DEVICE_DISK, FILE_DEVICE_CD_ROM };
    static UINT32 characteristics[WvlDiskMediaTypes] = {
        FILE_REMOVABLE_MEDIA | FILE_FLOPPY_DISKETTE,
        0,
        FILE_REMOVABLE_MEDIA | FILE_READ_ONLY_DEVICE
      };
  
    DBG("Creating PDO...\n");

    /* Point to the disk details provided. */
    disk_ptr = disk__get_ptr(dev_ptr);

    /* Create the disk PDO. */
    status = IoCreateDevice(
        disk_ptr->DriverObj,
        sizeof (WV_S_DEV_EXT),
        NULL,
        disk_types[disk_ptr->Media],
        FILE_AUTOGENERATED_DEVICE_NAME |
          FILE_DEVICE_SECURE_OPEN |
          characteristics[disk_ptr->Media],
        FALSE,
        &dev_obj_ptr
      );
    if (!NT_SUCCESS(status)) {
        WvlError("IoCreateDevice", status);
        return NULL;
      }

    /* Set associations for the PDO, device, disk. */
    WvDevForDevObj(dev_obj_ptr, dev_ptr);
    dev_ptr->Self = dev_obj_ptr;
    KeInitializeEvent(&disk_ptr->SearchEvent, SynchronizationEvent, FALSE);
    KeInitializeSpinLock(&disk_ptr->SpinLock);

    /* Some device parameters. */
    dev_obj_ptr->Flags |= DO_DIRECT_IO;         /* FIXME? */
    dev_obj_ptr->Flags |= DO_POWER_INRUSH;      /* FIXME? */

    DBG("Done.\n");
    return dev_obj_ptr;
  }

/*
 * WV_S_DISK_FAT_EXTRA and WV_S_DISK_FAT_SUPER taken from
 * syslinux/memdisk/setup.c by H. Peter Anvin.  Licensed under the terms
 * of the GNU General Public License version 2 or later.
 */
#ifdef _MSC_VER
#  pragma pack(1)
#endif
struct WV_DISK_FAT_EXTRA {
    UCHAR bs_drvnum;
    UCHAR bs_resv1;
    UCHAR bs_bootsig;
    UINT32 bs_volid;
    char bs_vollab[11];
    char bs_filsystype[8];
  } __attribute__((packed));
typedef struct WV_DISK_FAT_EXTRA WV_S_DISK_FAT_EXTRA, * WV_SP_DISK_FAT_EXTRA;

struct WV_DISK_FAT_SUPER {
    UCHAR bs_jmpboot[3];
    char bs_oemname[8];
    UINT16 bpb_bytspersec;
    UCHAR bpb_secperclus;
    UINT16 bpb_rsvdseccnt;
    UCHAR bpb_numfats;
    UINT16 bpb_rootentcnt;
    UINT16 bpb_totsec16;
    UCHAR bpb_media;
    UINT16 bpb_fatsz16;
    UINT16 bpb_secpertrk;
    UINT16 bpb_numheads;
    UINT32 bpb_hiddsec;
    UINT32 bpb_totsec32;
    union {
        struct { WV_S_DISK_FAT_EXTRA extra; } fat16;
        struct {
            UINT32 bpb_fatsz32;
            UINT16 bpb_extflags;
            UINT16 bpb_fsver;
            UINT32 bpb_rootclus;
            UINT16 bpb_fsinfo;
            UINT16 bpb_bkbootsec;
            char bpb_reserved[12];
            /* Clever, eh?  Same fields, different offset... */
            WV_S_DISK_FAT_EXTRA extra;
          } fat32 __attribute__((packed));
      } x;
  } __attribute__((__packed__));
typedef struct WV_DISK_FAT_SUPER WV_S_DISK_FAT_SUPER, * WV_SP_DISK_FAT_SUPER;
#ifdef _MSC_VER
#  pragma pack()
#endif

/**
 * Attempt to guess a disk's geometry.
 *
 * @v boot_sect_ptr     The MBR or VBR with possible geometry clues.
 * @v disk_ptr          The disk to set the geometry for.
 */
WVL_M_LIB VOID disk__guess_geometry(
    IN WVL_AP_DISK_BOOT_SECT boot_sect_ptr,
    IN OUT WV_SP_DISK_T disk_ptr
  ) {
    UINT16 heads = 0, sects_per_track = 0, cylinders;
    WVL_SP_DISK_MBR as_mbr;

    if ((boot_sect_ptr == NULL) || (disk_ptr == NULL))
      return;

    /*
     * FAT superblock geometry checking taken from syslinux/memdisk/setup.c by
     * H. Peter Anvin.  Licensed under the terms of the GNU General Public
     * License version 2 or later.
     */
    {
        /*
         * Look for a FAT superblock and if we find something that looks
         * enough like one, use geometry from that.  This takes care of
         * megafloppy images and unpartitioned hard disks. 
         */
        WV_SP_DISK_FAT_EXTRA extra = NULL;
        WV_SP_DISK_FAT_SUPER fs = (WV_SP_DISK_FAT_SUPER) boot_sect_ptr;
  
        if (
            (fs->bpb_media == 0xf0 || fs->bpb_media >= 0xf8) &&
            (fs->bs_jmpboot[0] == 0xe9 || fs->bs_jmpboot[0] == 0xeb) &&
            fs->bpb_bytspersec == 512 &&
            fs->bpb_numheads >= 1 &&
            fs->bpb_numheads <= 256 &&
            fs->bpb_secpertrk >= 1 &&
            fs->bpb_secpertrk <= 63
          ) {
            extra = fs->bpb_fatsz16 ? &fs->x.fat16.extra : &fs->x.fat32.extra;
            if (!(
                extra->bs_bootsig == 0x29 &&
                extra->bs_filsystype[0] == 'F' &&
                extra->bs_filsystype[1] == 'A' &&
                extra->bs_filsystype[2] == 'T'
              ))
              extra = NULL;
          }
        if (extra) {
            heads = fs->bpb_numheads;
            sects_per_track = fs->bpb_secpertrk;
          }
      } /* sub-scope */
    /*
     * If we couldn't parse a FAT superblock, try checking MBR params.
     * Logic derived from syslinux/memdisk/setup.c by H. Peter Anvin.
     */
    as_mbr = (WVL_SP_DISK_MBR) boot_sect_ptr;
    if (
        (heads == 0 ) &&
        (sects_per_track == 0) &&
        (as_mbr->mbr_sig == 0xAA55)
      ) {
        int i;

        for (i = 0; i < 4; i++) {
            if (
                !(as_mbr->partition[i].status & 0x7f) &&
                as_mbr->partition[i].type
              ) {
                UCHAR h, s;

                h = chs_head(as_mbr->partition[i].chs_start) + 1;
                s = chs_sector(as_mbr->partition[i].chs_start);

                if (heads < h)
                  heads = h;
                if (sects_per_track < s)
                  sects_per_track = s;

                h = chs_head(as_mbr->partition[i].chs_end) + 1;
                s = chs_sector(as_mbr->partition[i].chs_end);

                if (heads < h)
                  heads = h;
                if (sects_per_track < s)
                  sects_per_track = s;
              } /* if */
          } /* for */
      } /* if */
    /* If we were unable to guess, use some hopeful defaults. */
    if (!heads)
      heads = 255;
    if (!sects_per_track)
      sects_per_track = 63;
    /* Set params that are not already filled. */
    if (!disk_ptr->Heads)
      disk_ptr->Heads = heads;
    if (!disk_ptr->Sectors)
      disk_ptr->Sectors = sects_per_track;
    if (!disk_ptr->Cylinders)
      disk_ptr->Cylinders = disk_ptr->LBADiskSize / (heads * sects_per_track);
  }

/**
 * Create a new disk.
 *
 * @ret disk_ptr        The address of a new disk, or NULL for failure.
 *
 * See the header file for additional details.
 */
WVL_M_LIB WV_SP_DISK_T disk__create(void) {
    WV_SP_DEV_T dev_ptr;
    WV_SP_DISK_T disk_ptr;

    /*
     * Disk devices might be used for booting and should
     * not be allocated from a paged memory pool.
     */
    disk_ptr = wv_mallocz(sizeof *disk_ptr);
    if (disk_ptr == NULL)
      goto err_nodisk;

    dev_ptr = disk_ptr->Dev;
    WvDevInit(dev_ptr);

    /* Track the new disk in our global list. */
    ExInterlockedInsertTailList(
        &WvDiskList_,
        &disk_ptr->tracking,
        &WvDiskListLock_
      );
    /* Populate non-zero device defaults. */
    disk_ptr->disk_ops.MaxXferLen = WvDiskDefaultMaxXferLen_;
    disk_ptr->disk_ops.Init = WvDiskDefaultInit_;
    disk_ptr->disk_ops.Close = WvDiskDefaultClose_;
    dev_ptr->Ops.Close = WvDiskDevClose_;
    dev_ptr->Ops.CreatePdo = WvDiskCreatePdo_;
    dev_ptr->Ops.Free = WvDiskDevFree_;
    dev_ptr->Ops.Init = WvDiskDevInit_;
    dev_ptr->ext = disk_ptr;
    dev_ptr->IrpMj = &WvDiskIrpMj_;
    KeInitializeSpinLock(&disk_ptr->SpinLock);

    return disk_ptr;

    err_nodisk:

    return NULL;
  }

/**
 * Initialize the global, disk-common environment.
 *
 * @ret ntstatus        STATUS_SUCCESS or the NTSTATUS for a failure.
 */
NTSTATUS disk__module_init(void) {
    /* Initialize the global list of disks. */
    InitializeListHead(&WvDiskList_);
    KeInitializeSpinLock(&WvDiskListLock_);

    return STATUS_SUCCESS;
  }

/**
 * Default disk deletion operation.
 *
 * @v dev               Points to the disk device to delete.
 */
static VOID STDCALL WvDiskDevFree_(IN WV_SP_DEV_T dev) {
    WV_SP_DISK_T disk = disk__get_ptr(dev);

    /*
     * Track the disk deletion in our global list.  Unfortunately,
     * for now we have faith that a disk won't be deleted twice and
     * result in a race condition.  Something to keep in mind...
     */
    ExInterlockedRemoveHeadList(disk->tracking.Blink, &WvDiskListLock_);

    wv_free(disk);
  }

/* See header for details. */
NTSTATUS STDCALL disk__io(
    IN WV_SP_DEV_T dev,
    IN WVL_E_DISK_IO_MODE mode,
    IN LONGLONG start_sector,
    IN UINT32 sector_count,
    IN PUCHAR buffer,
    IN PIRP irp
  ) {
    WV_SP_DISK_T disk = disk__get_ptr(dev);

    if (disk->disk_ops.Io) {
        return disk->disk_ops.Io(
            dev,
            mode,
            start_sector,
            sector_count,
            buffer,
            irp
          );
      }
    return WvlIrpComplete(irp, 0, STATUS_DRIVER_INTERNAL_ERROR);
  }

/* See header for details. */
UINT32 disk__max_xfer_len(IN WV_SP_DISK_T disk) {
    /* Use the disk operation, if there is one. */
    if (disk->disk_ops.MaxXferLen)
      return disk->disk_ops.MaxXferLen(disk);
    return WvDiskDefaultMaxXferLen_(disk);
  }
